application: acme-store
version: 1
runtime: python27
api_version: 1
threadsafe: true


includes:
- api/apis.yaml
- interface/interface.yaml


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
